language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - pip install unittest
  - pip install requests2
script: python milestone_5_tests.py
branches:
  only:
    - master
