language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install unittest
  - pip install requests
script: python milestone_5_tests.py
branches:
  only:
    - master
